version: "3.3"
services:
  mongodb:
    image: mongo:5.0.8
    ports:
      - "27017:27017"
  vector:
    image: ashishcoolwar/omnykv2:1
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb


