version: "3.3"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb-omnyk-ashish
    restart: always
    volumes:
      - ashish-vol:/data/db
    ports:
      - "27017:27017"
  vector:
    build: .
    container_name: omnykv2java
    ports:
      - "8081:8080"
    volumes:
      - "./:/spring-boot"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb

volumes:
  ashish-vol:






