version: "3.3"
services:
  mongodb:
    image: mongo:5.0.8
    container_name: mongodb-omnyk
    ports:
      - "27017:27017"
  vector:
    build: .
    container_name: omnyk_service
    volumes:
      - /home/ec2-user:/data/db
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb


